services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pekko-bank
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./db/data:/var/lib/postgresql/data
